<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png"  width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction

Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.

Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

<a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01" target="_blank">Spacex DataSet</a>

### Store the dataset in database table

**it is highly recommended to manually load the table using the database console LOAD tool in DB2**.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload.png">

Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the  dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new table as follows:

**SPACEXDATASET**

**Follow these steps while using old DB2 UI which is having Open Console Screen**

**Note:While loading Spacex dataset, ensure that detect datatypes is disabled. Later click on the pencil icon(edit option).**

1.  Change the Date Format by manually typing DD-MM-YYYY and timestamp format as DD-MM-YYYY HH\:MM:SS

2.  Change the PAYLOAD_MASS\_\_KG\_  datatype  to INTEGER.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload2.png">

**Changes to be considered when having DB2 instance with the new UI having Go to UI screen**

*   Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">link</a> for viewing  the new  Go to UI screen.

*   Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.

*   Later browse for the downloaded spacex file.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800"/>

*   Once done select the schema andload the file.

 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800"/>

In [1]:
!pip install sqlalchemy==1.3.9
!pip install ibm_db_sa

Requirement already satisfied: sqlalchemy==1.3.9 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (1.3.9)
Requirement already satisfied: ibm_db_sa in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (0.3.6)
Requirement already satisfied: ibm-db>=2.0.0 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibm_db_sa) (3.0.4)
Requirement already satisfied: sqlalchemy>=0.7.3 in /opt/conda/envs/Python-3.8-main/lib/python3.8/site-packages (from ibm_db_sa) (1.3.9)

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [2]:
conda install -c conda-forge ipython-sql

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /opt/conda/envs/Python-3.8-main

  added / updated specs:
    - ipython-sql


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    certifi-2021.5.30          |   py38h578d9bd_0         141 KB  conda-forge
    ipython-sql-0.3.9          |py38h32f6830_1002          27 KB  conda-forge
    openssl-1.1.1k             |       h7f98852_0         2.1 MB  conda-forge
    prettytable-2.1.0          |     pyhd8ed1ab_0          23 KB  conda-forge
    python_abi-3.8             |           2_cp38           4 KB  conda-forge
    sqlparse-0.4.1             |     pyh9f0ad1d_0          34 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         2.3 MB

The following NEW packages will be INSTALLED:

  ipython-sql        conda-forge/linux-64::ipython-sql-0.3.9-py38h32f6830_1002
  prettytable        conda-forge/noarch::prettytable-2.1.0-pyhd8ed1ab_0
  python_abi         conda-forge/linux-64::python_abi-3.8-2_cp38
  sqlparse           conda-forge/noarch::sqlparse-0.4.1-pyh9f0ad1d_0

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi            pkgs/main::certifi-2021.5.30-py38h06a~ --> conda-forge::certifi-2021.5.30-py38h578d9bd_0
  openssl              pkgs/main::openssl-1.1.1k-h27cfd23_0 --> conda-forge::openssl-1.1.1k-h7f98852_0



Downloading and Extracting Packages
certifi-2021.5.30    | 141 KB    | ##################################### | 100%
python_abi-3.8       | 4 KB      | ##################################### | 100%
openssl-1.1.1k       | 2.1 MB    | ##################################### | 100%
prettytable-2.1.0    | 23 KB     | ##################################### | 100%
sqlparse-0.4.1       | 34 KB     | ##################################### | 100%
ipython-sql-0.3.9    | 27 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [2]:
%load_ext sql

**DB2 magic in case of old UI service credentials.**

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance before. From the **uri** field of your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_edX/images/URI.jpg">

in the following format

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name**

**DB2 magic in case of new UI service credentials.**

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png" width=600>  

*   Use the following format.

*   Add security=SSL at the end

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL**

In [3]:
%sql ibm_db_sa://hbp85526:ml7s93w43pdx20-h@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB

DB2/LINUXX8664

'Connected: hbp85526@BLUDB'

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

### Task 1

##### Display the names of the unique launch sites  in the space mission

In [4]:
# to verify if all table was loaded successfully
%sql SELECT * FROM SYSCAT.TABLES WHERE TABNAME = 'SPACEXDATASET'

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('HBP85526', 'SPACEXDATASET', 'HBP85526', 'U', 'T', 'N', None, None, None, None, datetime.datetime(2021, 8, 4, 8, 53, 41, 209094), datetime.datetime(2021, 8, 4, 8, 53, 41, 209094), datetime.datetime(2021, 8, 4, 8, 53, 41, 209094), datetime.datetime(2021, 8, 4, 8, 54, 34, 683314), 10, 20, 455, 101, 1, 0, 2, -1, -1, -1, 0, 'hbp85526space1', None, None, 0, 0, 0, 0, 0, 0, 0, 'N', 'YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY', 1, ' ', '0', -1, 'N', ' ', None, 'R', ' ', 'N', '                                ', None, 'N', ' ', 'F', None, 0, 'N', 999, 0, 0.0, 150, 0.0, None, 1208, 'SYSIBM', 'IDENTITY', 'SYSIBM', 'IDENTITY', ' ', 0, datetime.datetime(2021, 8, 4, 8, 53, 41, 209094), 0, ' ', None, None, 'N', 'HBP85526', ' ', ' ', ' ', datetime.date(1, 1, 1), ' ', 'N', 'R', 'N', -1.0, None)]

In [5]:
# query to retrieve the number of columns in the SPACEXDATASET table
%sql SELECT COUNT(*) FROM SYSCAT.COLUMNS WHERE TABNAME = 'SPACEXDATASET'

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('10'),)]

In [9]:
%sql SELECT DISTINCT (NAME), COLTYPE, LENGTH FROM SYSIBM.SYSCOLUMNS WHERE TBNAME = 'SPACEXDATASET'

The number of unique launch sites is given below:
 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('BOOSTER_VERSION', 'VARCHAR ', 14),
 ('CUSTOMER', 'VARCHAR ', 57),
 ('DATE', 'DATE    ', 4),
 ('LANDING__OUTCOME', 'VARCHAR ', 22),
 ('LAUNCH_SITE', 'VARCHAR ', 12),
 ('MISSION_OUTCOME', 'VARCHAR ', 32),
 ('ORBIT', 'VARCHAR ', 11),
 ('PAYLOAD', 'VARCHAR ', 61),
 ('PAYLOAD_MASS__KG_', 'INTEGER ', 4),
 ('TIME__UTC_', 'VARCHAR ', 8)]

In [10]:
%sql SELECT DISTINCT (launch_site) FROM SPACEXDATASET;

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('CCAFS LC-40',),
 ('CCAFS SLC-40',),
 ('CCAFSSLC-40',),
 ('KSC LC-39A',),
 ('VAFB SLC-4E',)]

### Task 2

##### Display 5 records where launch sites begin with the string 'CCA'

In [11]:
%%sql 
SELECT BOOSTER_VERSION, CUSTOMER, launch_site, LANDING__OUTCOME, PAYLOAD_MASS__KG_  
    FROM SPACEXDATASET 
    WHERE launch_site LIKE '%CCA%'  LIMIT 5;

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('F9 v1.0  B0003', 'SpaceX', 'CCAFS LC-40', 'Failure (parachute)', 0),
 ('F9 v1.0  B0004', 'NASA (COTS) NRO', 'CCAFS LC-40', 'Failure (parachute)', 0),
 ('F9 v1.0  B0005', 'NASA (COTS)', 'CCAFS LC-40', 'No attempt', 525),
 ('F9 v1.0  B0006', 'NASA (CRS)', 'CCAFS LC-40', 'No attempt', 500),
 ('F9 v1.0  B0007', 'NASA (CRS)', 'CCAFS LC-40', 'No attempt', 677)]

### Task 3

##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [ ]:
%%sql 
SELECT SUM(PAYLOAD_MASS_KG_) TotalPayloadMass 
    FROM SPACEXTBL 
    WHERE Customer = 'NASA (CRS)'

In [46]:
%sql SELECT SUM(payload_mass__kg_) AS Total_payload_mass, CUSTOMER FROM SPACEXDATASET GROUP BY CUSTOMER

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(7759, 'ABS Eutelsat'),
 (8963, 'AsiaSat'),
 (3669, 'Bulsatcom'),
 (3000, 'CONAE'),
 (3130, 'CONAE, PlanetIQ, SpaceX'),
 (4200, 'Canadian Space Agency (CSA)'),
 (5600, 'EchoStar'),
 (5300, 'Es hailSat'),
 (2150, 'Hisdesat exactEarth SpaceX'),
 (6092, 'Hispasat  NovaWurks'),
 (6070, 'Inmarsat'),
 (6761, 'Intelsat'),
 (67200, 'Iridium Communications'),
 (6460, 'Iridium Communications GFZ ‚ NASA'),
 (3500, 'KT Corporation'),
 (500, 'MDA'),
 (12055, 'NASA (CCD)'),
 (12530, 'NASA (CCDev)'),
 (12500, 'NASA (CCP)'),
 (525, 'NASA (COTS)'),
 (0, 'NASA (COTS) NRO'),
 (45596, 'NASA (CRS)'),
 (2617, 'NASA (CRS), Kacific 1'),
 (12050, 'NASA (CTS)'),
 (362, 'NASA (LSP)'),
 (553, 'NASA (LSP) NOAA CNES'),
 (1192, 'NASA / NOAA / ESA / EUMETSAT'),
 (5300, 'NRO'),
 (475, 'NSPO'),
 (5000, 'Northrop Grumman'),
 (3350, 'Orbcomm'),
 (4850, 'PSN, SpaceIL / IAI'),
 (5500, 'Republic of Korea Army, Spaceflight Industries (BlackSky)'),
 (23355, 'SES'),
 (5200, 'SES EchoStar'),
 (9296, 'SKY Perfect JSAT Group'),
 (6956, 'Sky Perfect JSAT, Kacific 1'),
 (185220, 'SpaceX'),
 (31010, 'SpaceX, Planet Labs'),
 (15440, 'SpaceX, Planet Labs, PlanetIQ'),
 (14932, 'SpaceX, Spaceflight Industries (BlackSky), Planet Labs'),
 (6500, 'Spacecom'),
 (4000, 'Spaceflight Industries'),
 (14135, 'Telesat'),
 (5800, 'Telkom Indonesia'),
 (6425, 'Thaicom'),
 (3600, 'Thales-Alenia/BTRC'),
 (4707, 'Turkmenistan National Space Agency'),
 (4990, 'U.S. Air Force'),
 (570, 'U.S. Air Force NASA NOAA'),
 (4311, 'U.S. Space Force'),
 (4400, 'USAF'),
 (4311, 'USSF')]

### Task 4

##### Display average payload mass carried by booster version F9 v1.1

In [12]:
%sql SELECT AVG(payload_mass__kg_) AS AVG_PAYLOAD_MASS FROM SPACEXDATASET WHERE booster_version = 'F9 v1.1'

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('2928.400000'),)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.

*Hint:Use min function*

In [13]:
%sql SELECT MIN(Date) AS FIRST_SUCCESS_LANDING FROM SPACEXDATASET WHERE LANDING__OUTCOME LIKE '%Success (ground pad)%';

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(datetime.date(2015, 12, 22),)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [24]:
%%sql 
SELECT BOOSTER_VERSION, CUSTOMER, payload_mass__kg_, LANDING__OUTCOME
    FROM SPACEXDATASET 
    WHERE LANDING__OUTCOME LIKE '%Success (ground pad)%' and (payload_mass__kg_ BETWEEN 4000 AND 6000);

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('F9 FT B1032.1', 'NRO', 5300, 'Success (ground pad)'),
 ('F9 B4 B1040.1', 'U.S. Air Force', 4990, 'Success (ground pad)'),
 ('F9 B4 B1043.1', 'Northrop Grumman', 5000, 'Success (ground pad)')]

### Task 7

##### List the total number of successful and failure mission outcomes

In [ ]:
%%sql
SELECT(SELECT Count(Mission_Outcome) 
    FROM SPACEXTBL
    WHERE Mission_OutcomeLIKE'% Success %’) as Successful_Mission_Outcomes, 
    (SELECT Count(Mission_Outcome) 
    FROM SPACEXTBL 
    WHERE Mission_OutcomeLIKE '% Failure %’) as Failure_Mission_Coutcome

In [23]:
%sql SELECT COUNT(MISSION_OUTCOME) AS SUCCESSFUL_OUTCOME FROM SPACEXDATASET WHERE MISSION_OUTCOME LIKE '%Success%';

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('100'),)]

In [22]:
%sql SELECT COUNT(MISSION_OUTCOME) AS FAILURE_OUTCOME FROM SPACEXDATASET WHERE MISSION_OUTCOME LIKE '%Failure%';

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(Decimal('1'),)]

### Task 8

##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [42]:
%%sql 
SELECT BOOSTER_VERSION, (SELECT MAX(payload_mass__kg_) FROM SPACEXDATASET) AS MAX_PAYLOAD
    FROM SPACEXDATASET

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[('F9 v1.0  B0003', 15600),
 ('F9 v1.0  B0004', 15600),
 ('F9 v1.0  B0005', 15600),
 ('F9 v1.0  B0006', 15600),
 ('F9 v1.0  B0007', 15600),
 ('F9 v1.1  B1003', 15600),
 ('F9 v1.1', 15600),
 ('F9 v1.1', 15600),
 ('F9 v1.1', 15600),
 ('F9 v1.1', 15600),
 ('F9 v1.1', 15600),
 ('F9 v1.1 B1011', 15600),
 ('F9 v1.1 B1010', 15600),
 ('F9 v1.1 B1012', 15600),
 ('F9 v1.1 B1013', 15600),
 ('F9 v1.1 B1014', 15600),
 ('F9 v1.1 B1015', 15600),
 ('F9 v1.1 B1016', 15600),
 ('F9 v1.1 B1018', 15600),
 ('F9 FT B1019', 15600),
 ('F9 v1.1 B1017', 15600),
 ('F9 FT B1020', 15600),
 ('F9 FT B1021.1', 15600),
 ('F9 FT B1022', 15600),
 ('F9 FT B1023.1', 15600),
 ('F9 FT B1024', 15600),
 ('F9 FT B1025.1', 15600),
 ('F9 FT B1026', 15600),
 ('F9 FT B1029.1', 15600),
 ('F9 FT B1031.1', 15600),
 ('F9 FT B1030', 15600),
 ('F9 FT  B1021.2', 15600),
 ('F9 FT B1032.1', 15600),
 ('F9 FT B1034', 15600),
 ('F9 FT B1035.1', 15600),
 ('F9 FT  B1029.2', 15600),
 ('F9 FT B1036.1', 15600),
 ('F9 FT B1037', 15600),
 ('F9 B4 B1039.1', 15600),
 ('F9 FT B1038.1', 15600),
 ('F9 B4 B1040.1', 15600),
 ('F9 B4 B1041.1', 15600),
 ('F9 FT  B1031.2', 15600),
 ('F9 B4 B1042.1', 15600),
 ('F9 FT  B1035.2', 15600),
 ('F9 FT  B1036.2', 15600),
 ('F9 B4 B1043.1', 15600),
 ('F9 FT  B1032.2', 15600),
 ('F9 FT  B1038.2', 15600),
 ('F9 B4 B1044', 15600),
 ('F9 B4  B1041.2', 15600),
 ('F9 B4  B1039.2', 15600),
 ('F9 B4 B1045.1', 15600),
 ('F9 B5  B1046.1', 15600),
 ('F9 B4  B1043.2', 15600),
 ('F9 B4  B1040.2', 15600),
 ('F9 B4 B1045.2', 15600),
 ('F9 B5B1047.1', 15600),
 ('F9 B5B1048.1', 15600),
 ('F9 B5 B1046.2', 15600),
 ('F9 B5B1049.1', 15600),
 ('F9 B5 B1048.2', 15600),
 ('F9 B5 B1047.2', 15600),
 ('F9 B5 B1046.3', 15600),
 ('F9 B5B1050', 15600),
 ('F9 B5B1054', 15600),
 ('F9 B5 B1049.2', 15600),
 ('F9 B5 B1048.3', 15600),
 ('F9 B5B1051.1', 15600),
 ('F9 B5B1056.1', 15600),
 ('F9 B5 B1049.3', 15600),
 ('F9 B5 B1051.2', 15600),
 ('F9 B5 B1056.2', 15600),
 ('F9 B5 B1047.3', 15600),
 ('F9 B5 B1048.4', 15600),
 ('F9 B5B1059.1', 15600),
 ('F9 B5 B1056.3', 15600),
 ('F9 B5 B1049.4', 15600),
 ('F9 B5 B1046.4', 15600),
 ('F9 B5 B1051.3', 15600),
 ('F9 B5 B1056.4', 15600),
 ('F9 B5 B1059.2', 15600),
 ('F9 B5 B1048.5', 15600),
 ('F9 B5 B1051.4', 15600),
 ('F9 B5B1058.1', 15600),
 ('F9 B5 B1049.5', 15600),
 ('F9 B5 B1059.3', 15600),
 ('F9 B5B1060.1', 15600),
 ('F9 B5 B1058.2', 15600),
 ('F9 B5 B1051.5', 15600),
 ('F9 B5 B1049.6', 15600),
 ('F9 B5 B1059.4', 15600),
 ('F9 B5 B1060.2', 15600),
 ('F9 B5 B1058.3', 15600),
 ('F9 B5 B1051.6', 15600),
 ('F9 B5 B1060.3', 15600),
 ('F9 B5B1062.1', 15600),
 ('F9 B5B1061.1', 15600),
 ('F9 B5B1063.1', 15600),
 ('F9 B5 B1049.7', 15600),
 ('F9 B5 B1058.4', 15600)]

### Task 9

##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015

In [70]:
%%sql 
SELECT *
    FROM SPACEXDATASET
    WHERE LANDING__OUTCOME LIKE '%Failure%'
    AND YEAR(DATE) = '2015'

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(datetime.date(2015, 10, 1), '9:47:00', 'F9 v1.1 B1012', 'CCAFS LC-40', 'SpaceX CRS-5', 2395, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Failure (drone ship)'),
 (datetime.date(2015, 4, 14), '20:10:00', 'F9 v1.1 B1015', 'CCAFS LC-40', 'SpaceX CRS-6', 1898, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Failure (drone ship)')]

### Task 10

##### Rank the  count of  successful landing_outcomes between the date 2010-06-04 and 2017-03-20 in descending order.

In [ ]:
%%sql
SELECT DATENAME(month, DATEADD(month, MONTH(CONVERT(date, Date, 105)), 0) - 1) AS
Month, Booster_Version, Launch_Site, Landing_Outcome FROM SPACEXTBL WHERE
(Landing_Outcome LIKE N'%Success%') AND(YEAR(CONVERT(date, Date, 105))='2017')

In [61]:
%%sql 
SELECT * 
    FROM SPACEXDATASET 
    WHERE LANDING__OUTCOME LIKE '%Succes%' AND
    YEAR (DATE) < 2017;

 * ibm_db_sa://hbp85526:***@dashdb-txn-sbox-yp-lon02-07.services.eu-gb.bluemix.net:50000/BLUDB
Done.

[(datetime.date(2015, 12, 22), '1:29:00', 'F9 FT B1019', 'CCAFS LC-40', 'OG2 Mission 2  11 Orbcomm-OG2 satellites', 2034, 'LEO', 'Orbcomm', 'Success', 'Success (ground pad)'),
 (datetime.date(2016, 8, 4), '20:43:00', 'F9 FT B1021.1', 'CCAFS LC-40', 'SpaceX CRS-8', 3136, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (drone ship)'),
 (datetime.date(2016, 6, 5), '5:21:00', 'F9 FT B1022', 'CCAFS LC-40', 'JCSAT-14', 4696, 'GTO', 'SKY Perfect JSAT Group', 'Success', 'Success (drone ship)'),
 (datetime.date(2016, 5, 27), '21:39:00', 'F9 FT B1023.1', 'CCAFS LC-40', 'Thaicom 8', 3100, 'GTO', 'Thaicom', 'Success', 'Success (drone ship)'),
 (datetime.date(2016, 7, 18), '4:45:00', 'F9 FT B1025.1', 'CCAFS LC-40', 'SpaceX CRS-9', 2257, 'LEO (ISS)', 'NASA (CRS)', 'Success', 'Success (ground pad)'),
 (datetime.date(2016, 8, 14), '5:26:00', 'F9 FT B1026', 'CCAFS LC-40', 'JCSAT-16', 4600, 'GTO', 'SKY Perfect JSAT Group', 'Success', 'Success (drone ship)')]

### Reference Links

*   <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*   <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log

| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>